version: 2.1

orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@2.2.0

executors:
  docker-publisher:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm install pnpm
      - run:
          name: Install dependencies
          command: pnpm install

  publish-to-dockerhub:
    executor: docker-publisher
    environment:
      IMAGE_NAME: yourdockerhubusername/yourimagename:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - publish-to-dockerhub:
          requires:
            - build-and-test
